package com.datas.easyorder.db.entity;
// Generated 2018-2-7 13:32:29 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * CustomerToAddress generated by hbm2java
 */
@Entity
@Table(name = "customer_to_address", catalog = "ultimatelife")
public class CustomerToAddress implements java.io.Serializable {

	private Long id;
	@JsonIgnore
	private Customer customer;
	private String toAddress;
	private String toCity;
	private String toProvince;
	private String toCountry;
	private String toPhone;
	private String toName;
	private String toEmail;
	private String toPostcode;
	private String toDistrict;
	@JsonIgnore
	private Set<Customer> customers = new HashSet<Customer>(0);

	public CustomerToAddress() {
	}

	public CustomerToAddress(Customer customer) {
		this.customer = customer;
	}

	public CustomerToAddress(Customer customer, String toAddress, String toCity, String toProvince, String toCountry,
			String toPhone, String toName, String toEmail,  String toDistrict,String toPostcode, Set<Customer> customers) {
		this.customer = customer;
		this.toAddress = toAddress;
		this.toCity = toCity;
		this.toProvince = toProvince;
		this.toCountry = toCountry;
		this.toPhone = toPhone;
		this.toName = toName;
		this.toEmail = toEmail;
		this.toDistrict = toDistrict;
		this.toPostcode = toPostcode;
		this.customers = customers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "to_address", length = 1024)
	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	@Column(name = "to_city", length = 1024)
	public String getToCity() {
		return this.toCity;
	}

	public void setToCity(String toCity) {
		this.toCity = toCity;
	}

	@Column(name = "to_province", length = 1024)
	public String getToProvince() {
		return this.toProvince;
	}

	public void setToProvince(String toProvince) {
		this.toProvince = toProvince;
	}

	@Column(name = "to_country", length = 1024)
	public String getToCountry() {
		return this.toCountry;
	}
	@Column(name = "to_district", length = 256)
	public String getToDistrict() {
		return toDistrict;
	}

	public void setToDistrict(String toDistrict) {
		this.toDistrict = toDistrict;
	}

	public void setToCountry(String toCountry) {
		this.toCountry = toCountry;
	}

	@Column(name = "to_phone", length = 1024)
	public String getToPhone() {
		return this.toPhone;
	}

	public void setToPhone(String toPhone) {
		this.toPhone = toPhone;
	}

	@Column(name = "to_name", length = 1024)
	public String getToName() {
		return this.toName;
	}

	public void setToName(String toName) {
		this.toName = toName;
	}

	@Column(name = "to_email", length = 1024)
	public String getToEmail() {
		return this.toEmail;
	}

	public void setToEmail(String toEmail) {
		this.toEmail = toEmail;
	}

	@Column(name = "to_postcode")
	public String getToPostcode() {
		return this.toPostcode;
	}

	public void setToPostcode(String toPostcode) {
		this.toPostcode = toPostcode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerToAddress")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
