package com.datas.easyorder.db.entity;
// Generated 2018-3-7 11:20:55 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CustomerFromAddress generated by hbm2java
 */
@Entity
@Table(name = "customer_from_address", catalog = "ultimatelife")
public class CustomerFromAddress implements java.io.Serializable {

	private Long id;
	private Customer customer;
	private String fromAddress;
	private String fromCity;
	private String fromProvince;
	private String fromCountry;
	private String fromPhone;
	private String fromName;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public CustomerFromAddress() {
	}

	public CustomerFromAddress(Customer customer) {
		this.customer = customer;
	}

	public CustomerFromAddress(Customer customer, String fromAddress, String fromCity, String fromProvince,
			String fromCountry, String fromPhone, String fromName, Set<Customer> customers) {
		this.customer = customer;
		this.fromAddress = fromAddress;
		this.fromCity = fromCity;
		this.fromProvince = fromProvince;
		this.fromCountry = fromCountry;
		this.fromPhone = fromPhone;
		this.fromName = fromName;
		this.customers = customers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "from_address", length = 1024)
	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	@Column(name = "from_city", length = 1024)
	public String getFromCity() {
		return this.fromCity;
	}

	public void setFromCity(String fromCity) {
		this.fromCity = fromCity;
	}

	@Column(name = "from_province", length = 1024)
	public String getFromProvince() {
		return this.fromProvince;
	}

	public void setFromProvince(String fromProvince) {
		this.fromProvince = fromProvince;
	}

	@Column(name = "from_country", length = 1024)
	public String getFromCountry() {
		return this.fromCountry;
	}

	public void setFromCountry(String fromCountry) {
		this.fromCountry = fromCountry;
	}

	@Column(name = "from_phone", length = 1024)
	public String getFromPhone() {
		return this.fromPhone;
	}

	public void setFromPhone(String fromPhone) {
		this.fromPhone = fromPhone;
	}

	@Column(name = "from_name", length = 1024)
	public String getFromName() {
		return this.fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerFromAddress")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
