package com.datas.easyorder.db.entity;
// Generated 2018-10-4 15:36:49 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductStockHistory generated by hbm2java
 */
@Entity
@Table(name = "product_stock_history", catalog = "yomi")
public class ProductStockHistory implements java.io.Serializable {

	private Long id;
	private Branch branch;
	private Product product;
	private String productNameEn;
	private Double qty;
	private Integer unit;
	private Integer unitQty;
	private Double cost;
	private Double price;
	private Date createTime;

	public ProductStockHistory() {
	}

	public ProductStockHistory(Product product) {
		this.product = product;
	}

	public ProductStockHistory(Branch branch, Product product, String productNameEn, Double qty, Integer unit,
			Integer unitQty, Double cost, Double price, Date createTime) {
		this.branch = branch;
		this.product = product;
		this.productNameEn = productNameEn;
		this.qty = qty;
		this.unit = unit;
		this.unitQty = unitQty;
		this.cost = cost;
		this.price = price;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "product_name_en", length = 1024)
	public String getProductNameEn() {
		return this.productNameEn;
	}

	public void setProductNameEn(String productNameEn) {
		this.productNameEn = productNameEn;
	}

	@Column(name = "qty", precision = 10)
	public Double getQty() {
		return this.qty;
	}

	public void setQty(Double qty) {
		this.qty = qty;
	}

	@Column(name = "unit")
	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

	@Column(name = "unit_qty")
	public Integer getUnitQty() {
		return this.unitQty;
	}

	public void setUnitQty(Integer unitQty) {
		this.unitQty = unitQty;
	}

	@Column(name = "cost", precision = 10)
	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	@Column(name = "price", precision = 10)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
