package com.datas.easyorder.db.entity;
// Generated 2018-3-7 11:20:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductAttr generated by hbm2java
 */
@Entity
@Table(name = "product_attr", catalog = "yomi")
public class ProductAttr implements java.io.Serializable {

	private Long id;
	private Product product;
	private ProductAttrKey productAttrKey;
	private ProductAttrValue productAttrValue;

	public ProductAttr() {
	}

	public ProductAttr(Product product, ProductAttrKey productAttrKey, ProductAttrValue productAttrValue) {
		this.product = product;
		this.productAttrKey = productAttrKey;
		this.productAttrValue = productAttrValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_attr_key_id")
	public ProductAttrKey getProductAttrKey() {
		return this.productAttrKey;
	}

	public void setProductAttrKey(ProductAttrKey productAttrKey) {
		this.productAttrKey = productAttrKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_attr_value_id")
	public ProductAttrValue getProductAttrValue() {
		return this.productAttrValue;
	}

	public void setProductAttrValue(ProductAttrValue productAttrValue) {
		this.productAttrValue = productAttrValue;
	}

}
