package com.datas.easyorder.db.entity;
// Generated 2018-3-7 11:20:55 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ProductAttrValue generated by hbm2java
 */
@Entity
@Table(name = "product_attr_value", catalog = "yomi")
public class ProductAttrValue implements java.io.Serializable {

	private Long id;
	@JsonIgnore
	private ProductAttrKey productAttrKey;
	private String attrValue;
	@JsonIgnore
	private Set<ProductAttr> productAttrs = new HashSet<ProductAttr>(0);

	public ProductAttrValue() {
	}

	public ProductAttrValue(ProductAttrKey productAttrKey) {
		this.productAttrKey = productAttrKey;
	}

	public ProductAttrValue(ProductAttrKey productAttrKey, String attrValue, Set<ProductAttr> productAttrs) {
		this.productAttrKey = productAttrKey;
		this.attrValue = attrValue;
		this.productAttrs = productAttrs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_attr_key_id", nullable = false)
	public ProductAttrKey getProductAttrKey() {
		return this.productAttrKey;
	}

	public void setProductAttrKey(ProductAttrKey productAttrKey) {
		this.productAttrKey = productAttrKey;
	}

	@Column(name = "attr_value", length = 1024)
	public String getAttrValue() {
		return this.attrValue;
	}

	public void setAttrValue(String attrValue) {
		this.attrValue = attrValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productAttrValue")
	public Set<ProductAttr> getProductAttrs() {
		return this.productAttrs;
	}

	public void setProductAttrs(Set<ProductAttr> productAttrs) {
		this.productAttrs = productAttrs;
	}

}
