package com.datas.easyorder.db.entity;
// Generated 2018-9-27 12:33:29 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * RankCustomer generated by hbm2java
 */
@Entity
@Table(name = "rank_customer", catalog = "yomi")
public class RankCustomer implements java.io.Serializable {

	private Long id;
	private String rankLevel;
	private String rankDesc;
	@JsonIgnore
	private Set<RankProductPrice> rankProductPrices = new HashSet<RankProductPrice>(0);
	@JsonIgnore
	private Set<Customer> customers = new HashSet<Customer>(0);

	public RankCustomer() {
	}

	public RankCustomer(String rankLevel) {
		this.rankLevel = rankLevel;
	}

	public RankCustomer(String rankLevel, String rankDesc, Set<RankProductPrice> rankProductPrices,
			Set<Customer> customers) {
		this.rankLevel = rankLevel;
		this.rankDesc = rankDesc;
		this.rankProductPrices = rankProductPrices;
		this.customers = customers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "rank_level", nullable = false)
	public String getRankLevel() {
		return this.rankLevel;
	}

	public void setRankLevel(String rankLevel) {
		this.rankLevel = rankLevel;
	}

	@Column(name = "rank_desc", length = 1024)
	public String getRankDesc() {
		return this.rankDesc;
	}

	public void setRankDesc(String rankDesc) {
		this.rankDesc = rankDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rankCustomer")
	public Set<RankProductPrice> getRankProductPrices() {
		return this.rankProductPrices;
	}

	public void setRankProductPrices(Set<RankProductPrice> rankProductPrices) {
		this.rankProductPrices = rankProductPrices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rankCustomer")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
