package com.datas.easyorder.db.entity;
// Generated 2018-9-28 16:02:05 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupplierOrder generated by hbm2java
 */
@Entity
@Table(name = "supplier_order", catalog = "yomi")
public class SupplierOrder implements java.io.Serializable {

	private Long id;
	private Supplier supplier;
	private User user;
	private String payType;
	private Integer isPaid;
	private double totalProductPrice;
	private Double totalFreight;
	private Integer status;
	private Date createTime;
	private Date modifyTime;
	private String supplierCompanyName;
	private String supplierContactName;
	private String supplierEmail;
	private String supplierPhone;
	private String supplierAddress;
	private String adminMsg;
	private Set<SupplierOrderItem> supplierOrderItems = new HashSet<SupplierOrderItem>(0);

	public SupplierOrder() {
	}

	public SupplierOrder(Supplier supplier, double totalProductPrice) {
		this.supplier = supplier;
		this.totalProductPrice = totalProductPrice;
	}

	public SupplierOrder(Supplier supplier, User user, String payType, Integer isPaid, double totalProductPrice,
			Double totalFreight, Integer status, Date createTime, Date modifyTime, String supplierCompanyName,
			String supplierContactName, String supplierEmail, String supplierPhone, String supplierAddress,
			String adminMsg, Set<SupplierOrderItem> supplierOrderItems) {
		this.supplier = supplier;
		this.user = user;
		this.payType = payType;
		this.isPaid = isPaid;
		this.totalProductPrice = totalProductPrice;
		this.totalFreight = totalFreight;
		this.status = status;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.supplierCompanyName = supplierCompanyName;
		this.supplierContactName = supplierContactName;
		this.supplierEmail = supplierEmail;
		this.supplierPhone = supplierPhone;
		this.supplierAddress = supplierAddress;
		this.adminMsg = adminMsg;
		this.supplierOrderItems = supplierOrderItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_id", nullable = false)
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "pay_type", length = 45)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "is_paid")
	public Integer getIsPaid() {
		return this.isPaid;
	}

	public void setIsPaid(Integer isPaid) {
		this.isPaid = isPaid;
	}

	@Column(name = "total_product_price", nullable = false, precision = 10)
	public double getTotalProductPrice() {
		return this.totalProductPrice;
	}

	public void setTotalProductPrice(double totalProductPrice) {
		this.totalProductPrice = totalProductPrice;
	}

	@Column(name = "total_freight", precision = 10)
	public Double getTotalFreight() {
		return this.totalFreight;
	}

	public void setTotalFreight(Double totalFreight) {
		this.totalFreight = totalFreight;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "supplier_company_name", length = 1024)
	public String getSupplierCompanyName() {
		return this.supplierCompanyName;
	}

	public void setSupplierCompanyName(String supplierCompanyName) {
		this.supplierCompanyName = supplierCompanyName;
	}

	@Column(name = "supplier_contact_name", length = 1024)
	public String getSupplierContactName() {
		return this.supplierContactName;
	}

	public void setSupplierContactName(String supplierContactName) {
		this.supplierContactName = supplierContactName;
	}

	@Column(name = "supplier_email", length = 1024)
	public String getSupplierEmail() {
		return this.supplierEmail;
	}

	public void setSupplierEmail(String supplierEmail) {
		this.supplierEmail = supplierEmail;
	}

	@Column(name = "supplier_phone", length = 1024)
	public String getSupplierPhone() {
		return this.supplierPhone;
	}

	public void setSupplierPhone(String supplierPhone) {
		this.supplierPhone = supplierPhone;
	}

	@Column(name = "supplier_address", length = 1024)
	public String getSupplierAddress() {
		return this.supplierAddress;
	}

	public void setSupplierAddress(String supplierAddress) {
		this.supplierAddress = supplierAddress;
	}

	@Column(name = "admin_msg", length = 1024)
	public String getAdminMsg() {
		return this.adminMsg;
	}

	public void setAdminMsg(String adminMsg) {
		this.adminMsg = adminMsg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplierOrder")
	public Set<SupplierOrderItem> getSupplierOrderItems() {
		return this.supplierOrderItems;
	}

	public void setSupplierOrderItems(Set<SupplierOrderItem> supplierOrderItems) {
		this.supplierOrderItems = supplierOrderItems;
	}

}
