package com.datas.easyorder.db.entity;
// Generated 2018-10-4 15:36:49 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "yomi")
public class Supplier implements java.io.Serializable {

	private Long id;
	private String companyName;
	private String phone;
	private String contactName;
	private String mobile;
	private String address;
	private String website;
	private String memo;
	private Date createTime;
	private Date modifyTime;
	private Byte status;
	private String userName;
	private String password;
	private Set<SupplierOrder> supplierOrders = new HashSet<SupplierOrder>(0);
	private Set<SupplierProduct> supplierProducts = new HashSet<SupplierProduct>(0);

	public Supplier() {
	}

	public Supplier(String companyName, String phone, String contactName, String mobile, String address, String website,
			String memo, Date createTime, Date modifyTime, Byte status, String userName, String password,
			Set<SupplierOrder> supplierOrders, Set<SupplierProduct> supplierProducts) {
		this.companyName = companyName;
		this.phone = phone;
		this.contactName = contactName;
		this.mobile = mobile;
		this.address = address;
		this.website = website;
		this.memo = memo;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.status = status;
		this.userName = userName;
		this.password = password;
		this.supplierOrders = supplierOrders;
		this.supplierProducts = supplierProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "company_name")
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "contact_name")
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "mobile")
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "website")
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "memo")
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<SupplierOrder> getSupplierOrders() {
		return this.supplierOrders;
	}

	public void setSupplierOrders(Set<SupplierOrder> supplierOrders) {
		this.supplierOrders = supplierOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<SupplierProduct> getSupplierProducts() {
		return this.supplierProducts;
	}

	public void setSupplierProducts(Set<SupplierProduct> supplierProducts) {
		this.supplierProducts = supplierProducts;
	}

}
