package com.datas.easyorder.db.entity;
// Generated 2018-3-7 11:20:55 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserCompany generated by hbm2java
 */
@Entity
@Table(name = "user_company", catalog = "yomi")
public class UserCompany implements java.io.Serializable {

	private Long id;
	private String name;
	private String code;
	private String gstNo;
	private String description;
	private String type;
	private String website;
	private String email;
	private String tel;
	private String fax;
	private String status;
	private String language;
	private Integer stuffNumber;
	private String address;
	private String mobile;
	private String bankAccount;
	private Date createTime;
	private Date modifyTime;
	private String quotationTermsConditions;
	private String invoiceTermsConditions;
	private String sendingMail;
	private String sendingMailSmtp;
	private String sendingMailPassword;
	private String sendingMailTemplate;
	private String sendingMailSubject;
	private String sendingMailCc;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);
	private Set<User> users = new HashSet<User>(0);

	public UserCompany() {
	}

	public UserCompany(String name, String code, String gstNo, String description, String type, String website,
			String email, String tel, String fax, String status, String language, Integer stuffNumber, String address,
			String mobile, String bankAccount, Date createTime, Date modifyTime, String quotationTermsConditions,
			String invoiceTermsConditions, String sendingMail, String sendingMailSmtp, String sendingMailPassword,
			String sendingMailTemplate, String sendingMailSubject, String sendingMailCc, Set<Invoice> invoices,
			Set<User> users) {
		this.name = name;
		this.code = code;
		this.gstNo = gstNo;
		this.description = description;
		this.type = type;
		this.website = website;
		this.email = email;
		this.tel = tel;
		this.fax = fax;
		this.status = status;
		this.language = language;
		this.stuffNumber = stuffNumber;
		this.address = address;
		this.mobile = mobile;
		this.bankAccount = bankAccount;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.quotationTermsConditions = quotationTermsConditions;
		this.invoiceTermsConditions = invoiceTermsConditions;
		this.sendingMail = sendingMail;
		this.sendingMailSmtp = sendingMailSmtp;
		this.sendingMailPassword = sendingMailPassword;
		this.sendingMailTemplate = sendingMailTemplate;
		this.sendingMailSubject = sendingMailSubject;
		this.sendingMailCc = sendingMailCc;
		this.invoices = invoices;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 512)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "gst_no")
	public String getGstNo() {
		return this.gstNo;
	}

	public void setGstNo(String gstNo) {
		this.gstNo = gstNo;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "website")
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "tel")
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "fax")
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "status", length = 11)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "language")
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "stuff_number")
	public Integer getStuffNumber() {
		return this.stuffNumber;
	}

	public void setStuffNumber(Integer stuffNumber) {
		this.stuffNumber = stuffNumber;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "mobile")
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "bank_account")
	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "quotation_terms_conditions")
	public String getQuotationTermsConditions() {
		return this.quotationTermsConditions;
	}

	public void setQuotationTermsConditions(String quotationTermsConditions) {
		this.quotationTermsConditions = quotationTermsConditions;
	}

	@Column(name = "invoice_terms_conditions")
	public String getInvoiceTermsConditions() {
		return this.invoiceTermsConditions;
	}

	public void setInvoiceTermsConditions(String invoiceTermsConditions) {
		this.invoiceTermsConditions = invoiceTermsConditions;
	}

	@Column(name = "sending_mail")
	public String getSendingMail() {
		return this.sendingMail;
	}

	public void setSendingMail(String sendingMail) {
		this.sendingMail = sendingMail;
	}

	@Column(name = "sending_mail_smtp")
	public String getSendingMailSmtp() {
		return this.sendingMailSmtp;
	}

	public void setSendingMailSmtp(String sendingMailSmtp) {
		this.sendingMailSmtp = sendingMailSmtp;
	}

	@Column(name = "sending_mail_password")
	public String getSendingMailPassword() {
		return this.sendingMailPassword;
	}

	public void setSendingMailPassword(String sendingMailPassword) {
		this.sendingMailPassword = sendingMailPassword;
	}

	@Column(name = "sending_mail_template", length = 65535)
	public String getSendingMailTemplate() {
		return this.sendingMailTemplate;
	}

	public void setSendingMailTemplate(String sendingMailTemplate) {
		this.sendingMailTemplate = sendingMailTemplate;
	}

	@Column(name = "sending_mail_subject", length = 500)
	public String getSendingMailSubject() {
		return this.sendingMailSubject;
	}

	public void setSendingMailSubject(String sendingMailSubject) {
		this.sendingMailSubject = sendingMailSubject;
	}

	@Column(name = "sending_mail_cc")
	public String getSendingMailCc() {
		return this.sendingMailCc;
	}

	public void setSendingMailCc(String sendingMailCc) {
		this.sendingMailCc = sendingMailCc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userCompany")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userCompany")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
